2025-08-19 19:07:44,651 - WARNING - /home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:547: FitFailedWarning:


170 fits failed out of a total of 250.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.20112 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.43244 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.21165 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.06676 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.43319 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.35536 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.56958 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.1979 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.56117 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.18675 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.39018 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.45004 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.26884 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.07221 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.16128 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.02754 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.23641 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.20442 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.19887 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.01651 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.50683 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.08483 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.57178 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.10268 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.32822 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.13577 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.31115 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.54052 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.27569 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.29578 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.59625 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.45632 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.53563 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/sklearn.py", line 1599, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 2100, in update
    _check_call(
  File "/home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: value 1.54013 for Parameter colsample_bytree exceed bound [0,1]
colsample_bytree: Subsample ratio of columns, resample on each tree construction.



2025-08-19 19:07:44,655 - WARNING - /home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/model_selection/_search.py:1051: UserWarning:

One or more of the test scores are non-finite: [0.63364484 0.61848484        nan        nan        nan 0.61894993
 0.61694687        nan 0.61184482 0.61318518        nan        nan
        nan        nan        nan        nan 0.60149795 0.61252119
        nan        nan        nan        nan        nan        nan
        nan        nan        nan 0.61869266        nan        nan
 0.61798261        nan 0.62471878        nan 0.60807977        nan
 0.61672164 0.62195235        nan        nan 0.61459464        nan
        nan        nan        nan        nan 0.61666911        nan
        nan        nan]


2025-08-19 19:07:44,665 - WARNING - /home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/xgboost/core.py:158: UserWarning:

[19:07:44] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.



2025-08-19 19:07:44,945 - WARNING - /home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.


2025-08-19 19:07:44,946 - WARNING - /home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.


2025-08-19 19:07:44,947 - WARNING - /home/askar/Desktop/Projects/breast_cancer/.venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.


